name: Renovate

permissions:
  contents: read

on:
  pull_request:

jobs:
  renovate:
    name: Validate config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run config validator
        run: npx --yes --package renovate -- renovate-config-validator renovate.json --strict
