name: Renovate

permissions:
  contents: read

on:
  pull_request:

jobs:
  renovate:
    name: Validate config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run config validator
        run: npx --yes --package renovate -- renovate-config-validator renovate.json --strict
